server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:7000/eureka
 #    defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
    register-with-eureka: false
  instance:
    instance-id: provider-user
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
turbine:
  # 配置监控的服务id，多个服务以逗号分隔
  app-config: provider-product,provider-user
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。
    cluster-config: "default"
  clusterNameExpression: new String("default")